name: Update all puppet-lint plugins

on:
  workflow_dispatch: {}
  #push:
  #  branches:
  #    - master

env:
  GIT_AUTHOR_NAME: pccibot
  GIT_AUTHOR_EMAIL: voxpupuli@users.noreply.github.com
  GIT_COMMITTER_NAME: pccibot
  GIT_COMMITTER_EMAIL: voxpupuli@users.noreply.github.com
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  GITHUB_BASE_URL: https://api.github.com

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Run msync against all modules
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Add SSH key
        run: |
            mkdir -p /home/runner/.ssh
            echo "${{ secrets.PCCI_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions
      - name: set git config
        run: git config --global user.email 'voxpupuli@users.noreply.github.com' && git config --global user.name 'pccibot'
      - name: Run msync
        env:
          # https://github.com/voxpupuli/modulesync?tab=readme-ov-file#submitting-prsmrs-to-github-or-gitlab
          GITHUB_TOKEN: '${{ secrets.PCCI_PAT_MODULESYNC_PR }}'
        run: |
          bundle exec msync update --verbose \
            --pr \
            --pr-labels modulesync \
            --pr-title "modulesync $(git describe)" \
            --message "modulesync $(git describe)"
